export default {
  columnCount: 4,
  actionButtons: ['delete', 'archive', 'cancel', 'edit', 'save'],
  schema: [
    {
      component: 'EfSpace',
      span: 3,
    },
    {
      component: 'EfTitle',
      span: 1,
      label: 'Example component:',
    },
    {
      id: 'name',
      span: 3,
      component: 'QInput',
      label: 'Superhero name',
      subLabel: 'Think of something cool.',
      required: true,
    },
    {
      id: 'md-input',
      component: 'EfMarkdown',
      span: 1,
      src: "```js\n{component: 'QInput'}\n```",
    },
    {
      id: 'powerOrigin',
      span: 3,
      component: 'QBtnToggle',
      spread: true,
      label: 'Power origin',
      subLabel: 'Where does your power come from?',
      options: [
        { label: 'Mutation', value: 'mutation' },
        { label: 'Self taught', value: 'self' },
        { label: 'By item', value: 'item' },
      ],
    },
    {
      id: 'md-btn-toggle',
      component: 'EfMarkdown',
      span: 1,
      src: "```js\n{component: 'QBtnToggle'}\n```",
    },
    {
      id: 'stamina',
      span: 3,
      component: 'QSlider',
      label: 'Stamina',
      min: 0,
      max: 100,
      default: 50,
      labelValue: val => `${val} stamina`,
      labelAlways: true,
    },
    {
      id: 'md-slider',
      component: 'EfMarkdown',
      span: 1,
      src: "```js\n{component: 'QSlider'}\n```",
    },
    {
      id: 'power',
      span: 3,
      component: 'QInput',
      type: 'number',
      parseInput: Number,
      label: 'Power',
      subLabel: 'Fill in a number.',
      suffix: 'PW',
    },
    {
      id: 'md-input-nr',
      component: 'EfMarkdown',
      span: 1,
      src:
        "```js\n{component: 'QInput'}\n```\n↳ But the input is saved as a number instead of a string.",
    },
    {
      id: 'roleModel',
      span: 3,
      component: 'QSelect',
      valueType: 'object',
      label: 'Role model',
      subLabel: 'Who do you look up to?',
      options: [
        { label: 'Steve Rogers/Captain America', value: 'captain-america' },
        { label: 'Tony Stark/Iron Man', value: 'iron-man' },
        { label: 'Thor Odinson', value: 'thor-odinson' },
        { label: 'Bruce Banner/The Incredible Hulk', value: 'the-incredible-hulk' },
        { label: 'Natasha Romanoff/Black Widow', value: 'black-widow' },
        { label: 'Clint Barton/Hawkeye', value: 'hawkeye' },
        { label: 'Pietro Maximoff/Quicksilver', value: 'quicksilver' },
        { label: 'Wanda Maximoff/Scarlet Witch', value: 'scarlet-witch' },
        { label: 'The Vision', value: 'the-vision' },
        { label: 'James Rhodes/War Machine (Iron Patriot)', value: 'war-machine' },
        { label: 'Sam Wilson/Falcon', value: 'falcon' },
        { label: 'Bucky Barnes/The Winter Soldier (White Wolf)', value: 'the-winter-soldier' },
        { label: "T'Challa/Black Panther", value: 'black-panther' },
        { label: 'Stephen Strange/Doctor Strange', value: 'doctor-strange' },
        { label: 'Peter Parker/Spider-Man', value: 'spider-man' },
        { label: 'Scott Lang/Ant-Man (Giant-Man)', value: 'ant-man' },
        { label: 'Hope van Dyne/Wasp', value: 'wasp' },
        { label: 'Carol Danvers/Captain Marvel', value: 'captain-marvel' },
        { label: 'Peter Quill/Star-Lord', value: 'star-lord' },
        { label: 'Gamora', value: 'gamora' },
        { label: 'Drax the Destroyer', value: 'drax-the-destroyer' },
        { label: 'Rocket (Raccoon)', value: 'rocket-raccoon' },
        { label: '(Baby, Teenage) Groot', value: 'groot' },
        { label: 'Mantis', value: 'mantis' },
        { label: 'Matthew Murdock/Daredevil', value: 'daredevil' },
        { label: 'Jessica Jones (Jewel)', value: 'jessica-jones' },
        { label: 'Carl Lucas/Luke Cage (Power Man)', value: 'luke-cage' },
        { label: 'Danny Rand/Iron Fist', value: 'iron-fist' },
        { label: 'Frank Castle/The Punisher', value: 'the-punisher' },
      ],
    },
    {
      id: 'md-select',
      component: 'EfMarkdown',
      span: 1,
      src: "```js\n{component: 'QSelect'}\n```",
    },
    {
      id: 'checkboxes',
      component: 'QOptionGroup',
      type: 'checkbox',
      span: 3,
      label: 'Check some boxes',
      options: [
        {
          label: 'Option 1',
          value: 'op1',
        },
        {
          label: 'Option 2',
          value: 'op2',
        },
        {
          label: 'Option 3',
          value: 'op3',
        },
      ],
      default: [],
    },
    {
      id: 'md-option-group',
      component: 'EfMarkdown',
      span: 1,
      src: "```js\n{component: 'QOptionGroup'}\n```",
    },
    {
      id: 'consent',
      component: 'QToggle',
      span: 3,
      label: 'Do you agree with our terms?',
      default: false,
    },
    {
      id: 'md-toggle',
      component: 'EfMarkdown',
      span: 1,
      src: "```js\n{component: 'QToggle'}\n```",
    },
    {
      id: 'submissionDate',
      component: 'EfInputDate',
      span: 3,
      label: 'Date of submission',
      valueType: 'date',
    },
    {
      id: 'md-input-date',
      component: 'EfMarkdown',
      span: 1,
      src: "```js\n{component: 'EfInputDate'}\n```",
    },
  ],
}
